#### 機械学習のための Numpy

In [71]:
import numpy as np

"""基本情報"""
x = np.array([[1,4],[3,3]])
print(x)
print(type(x))  
print(x.shape) # 次元をタプルで返す
print(x.size) # 全要素数
print(x.ndim) # 配列の次元数
print(x.dtype) # 配列のデータ型
print(x.nbytes) # 消費バイト数

[[1 4]
 [3 3]]
<class 'numpy.ndarray'>
(2, 2)
4
2
int32
16


In [72]:
"""行列式で判定　結果が0の場合は逆行列を持たない ※xは正方行列（行数と列数が等しい行列）の必要がある"""
np.linalg.det(x)

-9.000000000000002

In [73]:
"""逆行列
※xは正方行列（行数と列数が等しい行列）の必要がある
※回帰分析で使われる
"""
x_t = np.linalg.inv(x) 
x_t

array([[-0.33333333,  0.44444444],
       [ 0.33333333, -0.11111111]])

In [58]:
"""行列とその逆行列の積は単位行列となる"""
i = x.dot(x_t)
i

array([[1., 0.],
       [0., 1.]])

In [59]:
"""単位行列はこのようにも作れる"""
i = np.identity(2)
i

array([[1., 0.],
       [0., 1.]])

In [60]:
"""行列ｘに単位行列を掛けると結果はｘに等しくなる"""
x.dot(i)

array([[1., 4.],
       [3., 3.]])

In [61]:
"""消費バイト数比較  (-2147483647 < 扱う数字 < 2147483648) なら int32で十分でしょう"""
x = np.array([[1,2,3],[4,5,6]], dtype = np.uint32) # uint（符号なし整数）
print(x.nbytes)
x = np.array([[1,2,3],[4,5,6]], dtype = np.float)
print(x.nbytes)
x = np.array([[1,2,3],[4,5,6]], dtype = np.complex)
print(x.nbytes)
x = np.array([[1,2,3],[4,5,6]], dtype = np.int64)
print(x.nbytes)

""" int32 int64 の違いって何？
整数のタイプごとに、異なる範囲のストレージ容量がある
Int16 -- 2バイト-- (-32,768 to +32,767)
Int32 -- 4バイト-- (-2,147,483,648 to +2,147,483,647)
Int64 -- 8バイト-- (-9,223,372,036,854,775,808 to +9,223,372,036,854,775,807)
"""

24
48
96
48


In [62]:
"""astype属性を使い新たなdtypeの配列にコピー"""
x = np.array([[1,2,3],[4,5,6]], dtype = np.uint32) 
x_copy_int = x.astype(np.float)
print(x_copy_int)
x # 元の配列のdtypeは変わらない

[[1. 2. 3.]
 [4. 5. 6.]]


array([[1, 2, 3],
       [4, 5, 6]], dtype=uint32)

In [63]:
"""
dtypeを変えるだけで配列の大きさが80MBから40MBに縮小する。
その代わり、小数点以下の精度は低くなる。小数点以下16桁から7桁に。
"""
big_data = np.random.rand(100000,100)
print(big_data.nbytes)
big_data_new = big_data.astype(np.float32)
print(big_data_new.nbytes)

80000000
40000000


In [64]:
"""リストではこんな簡単に計算出来なくて、要素を反復する必要が"""
my_list = [2, 14, 6, 8]
my_array = np.asarray(my_list)
my_array + 2 #  

array([ 4, 16,  8, 10])

In [65]:
"""配列作成の便利方法（開始、終了、間隔）"""
x = np.arange(3,7,0.5)
x

array([3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5])

In [66]:
"""いくつに分割したいかわかっている場合"""
x = np.linspace(1.2, 40.5, num=20)
x

array([ 1.2       ,  3.26842105,  5.33684211,  7.40526316,  9.47368421,
       11.54210526, 13.61052632, 15.67894737, 17.74736842, 19.81578947,
       21.88421053, 23.95263158, 26.02105263, 28.08947368, 30.15789474,
       32.22631579, 34.29473684, 36.36315789, 38.43157895, 40.5       ])

In [67]:
"""対数スケールの等比等比数列を返す"""
np.geomspace(1, 625, num=5)

array([  1.,   5.,  25., 125., 625.])

In [68]:
"""
開始値と終了値の間を対数スケールで均等に値を並べた配列を返す
下の場合、開始値が10**3で終了値が10**4
"""
np.logspace(3, 4, num=5)

array([ 1000.        ,  1778.27941004,  3162.27766017,  5623.4132519 ,
       10000.        ])

In [69]:
"""上記例のような大きな値を避けるには常用対数を用いる"""
np.logspace(np.log10(3), np.log10(4), num=5)

array([3.        , 3.2237098 , 3.46410162, 3.72241944, 4.        ])

In [73]:
"""配列同士を高速に比較"""
x = np.array([1,2,3,4])
y = np.array([1,2,3,3])
x == y

array([ True,  True,  True, False])

In [75]:
"""2つの配列の全要素同士が一致するか否かを1つの値で返す"""
x = np.array([1,2,3,4,5,6,7,8,1,2,3,4,5,6,7,8,1,2,3,4,5,6,7,8,9,9,9,9])
y = np.array([1,2,3,4,5,6,7,8,1,2,3,4,5,6,7,8,1,2,3,4,5,6,7,8,9,9,8,9])
np.array_equal(x,y)

False

In [77]:
x > y

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False,  True,
       False])

In [80]:
"""論理比較（AND）"""
x = np.array([0, 1, 0, 0], dtype=bool)
y = np.array([1, 1, 0, 1], dtype=bool)
np.logical_and(x,y)

array([False,  True, False, False])

In [81]:
"""論理比較（OR）"""
x = np.array([12,16,57,11])
np.logical_or(x < 13, x > 50)

array([ True, False,  True,  True])

In [82]:
"""指数、三角関数"""
print(np.exp(x))
print(np.sin(x))

[1.62754791e+05 8.88611052e+06 5.68572000e+24 5.98741417e+04]
[-0.53657292 -0.28790332  0.43616476 -0.99999021]


In [86]:
"""行列を希望の形状に"""
x = np.arange(9)
print(x)
y = x.reshape((3, 3))
y

[0 1 2 3 4 5 6 7 8]


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [90]:
"""行列の転置"""
y.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [94]:
"""配列全体あるいは指定した軸沿いの和を返す
axisは作用させる次元を指定する
x軸:axis=0
y軸:axis=1
"""
x = np.arange(9).reshape((3,3))
print(x)
print(np.sum(x))
np.sum(x, axis=0)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
36


array([ 9, 12, 15])

In [95]:
"""配列全体あるいは指定した軸沿いの最小値を返す"""
np.amin(x)

0

In [97]:
"""配列全体あるいは指定した軸沿いの最大値を返す（NAN値を無視する）"""
np.nanmax(x)

8

In [96]:
"""配列全体あるいは指定した軸沿いのパーセンタイルを返す"""
np.percentile(x, 80)

"""パーセンタイルって何？
パーセンタイルは、データを大きさ順でならべて100個に区切り、  ⇒　いつも100個？
小さいほうからのどの位置にあるかを見るものです。
50パーセンタイルは、小さいほうから50/100のところにあるデータです。
"""

6.4

In [99]:
"""最大値のインデックスを取得"""
x = np.array([1,-21,3,-3])
np.argmax(x)

2

In [101]:
"""配列全体、あるいは指定した軸沿いの平均値を返す"""
x = np.array([[2,3,5],[20,12,4]])
np.mean(x, axis=0)

array([11. ,  7.5,  4.5])

In [103]:
"""配列全体、あるいは指定した軸沿いの中央値を返す"""
np.median(x)

"""中央値って何？
中央値あるいはメジアン、メディアンとは、データや集合の代表値の一つで、
順位が中央である値のこと。ただし、データの大きさが偶数の場合は、中央順位2個の値の算術平均をとる。
例えば5人の年齢10歳、32歳、96歳、100歳、105歳からなるデータの中央値は、順位が上からも下からも3である96（歳）となる。
0歳の子供が2人増えて7人になると、中央値は32歳となる。
"""

4.5

In [105]:
"""配列全体、あるいは指定した軸沿いの標準偏差を返す"""
np.std(x)

6.394442031083626

In [8]:
"""行列の掛け算はdot()を使う"""
c = np.ones((4, 4))
print(c)
c.dot(c)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [11]:
"""配列を垂直方向にスタックするvstack、水平方向はhstack、分割はvsplitとhsplit"""
y = np.arange(15).reshape(3,5)
x = np.arange(10).reshape(2,5)
new_array = np.vstack((y,x))
new_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9]])

In [25]:
"""各特徴の記述統計量を簡単に得る方法
サンプルサイズ，最小値，最大値，平均値，分散，歪度，尖度を求める
表示される variance は，デフォルトで ddof=1, numpy.var(x, ddof=1) すなわち，不偏分散
ddof=0 を指定すれば，不偏でない分散を表示
"""
from scipy.stats import describe
x = [1.2, 3.1, 4.6, 2.2, 5.7]
describe(x)

DescribeResult(nobs=5, minmax=(1.2, 5.7), mean=3.3599999999999994, variance=3.2729999999999997, skewness=0.14460191499270095, kurtosis=-1.3684571122281206)

In [24]:
"""各特徴の記述統計量を簡単に得る方法続き"""
x = np.random.rand(100,10)
n, min_max, mean, var, skew, kurt = stats.describe(x)
new_array = np.vstack((mean,var,skew,kurt,min_max[0],min_max[1]))
new_array.T

array([[ 0.53940477,  0.08765163, -0.0127855 , -1.30140606,  0.0262327 ,
         0.9918206 ],
       [ 0.49527034,  0.08463585, -0.05020535, -1.29965711,  0.0071916 ,
         0.99815204],
       [ 0.52020961,  0.08138131, -0.11252271, -1.19548597,  0.00337193,
         0.99565851],
       [ 0.51641973,  0.07636803, -0.04280076, -1.0448318 ,  0.00203595,
         0.99569915],
       [ 0.50571968,  0.08741635, -0.01652783, -1.27578067,  0.01665709,
         0.99511069],
       [ 0.46263657,  0.10099383,  0.17023862, -1.39752425,  0.01858615,
         0.99391715],
       [ 0.51773774,  0.08553457, -0.09834773, -1.33141603,  0.01878073,
         0.99070543],
       [ 0.47727274,  0.07847052,  0.20258956, -1.16546062,  0.00322962,
         0.99840007],
       [ 0.50702992,  0.07662201, -0.02919445, -1.24405648,  0.01353699,
         0.98311133],
       [ 0.49267839,  0.07219836,  0.01351953, -1.08354985,  0.01694832,
         0.97836142]])

In [30]:
"""NaN値を置換する際にとても便利"""
x = np.arange(25, dtype = float).reshape(5,5)
x[x<5] = np.nan
print(x)
# nanを各列の平均値で上書き
np.where(np.isnan(x), ma.array(x, mask=np.isnan(x)).mean(axis=0), x)

[[nan nan nan nan nan]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]
 [20. 21. 22. 23. 24.]]


array([[12.5, 13.5, 14.5, 15.5, 16.5],
       [ 5. ,  6. ,  7. ,  8. ,  9. ],
       [10. , 11. , 12. , 13. , 14. ],
       [15. , 16. , 17. , 18. , 19. ],
       [20. , 21. , 22. , 23. , 24. ]])

In [42]:
"""多次元配列のインデックス付けとスライス"""
x = np.reshape(np.arange(16),(4,4))
print(x)
print(x[1:3,1:3])
x[[0,1,2],[0,1,3]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 5  6]
 [ 9 10]]


array([ 0,  5, 11])

In [46]:
"""linalg.multi_dot() ２つ以上の配列の掛け算を１つの関数で実行したい場合に最適化で速い
以下のコードで、実行時間を比較
"""
from numpy.linalg import multi_dot
import time

a = np.arange(120000).reshape(400,300)
b = np.arange(150000).reshape(300,500)
c = np.arange(200000).reshape(500,400)

start = time.time()
multi_dot([a,b,c])
ft = time.time()-start
print('Multi_dot tooks', time.time()-start,'seconds.')

start_ft = time.time()
a.dot(b).dot(c)
print('Chain dot tooks', time.time()-start_ft,'seconds.')

Multi_dot tooks 0.292816162109375 seconds.
Chain dot tooks 0.306809663772583 seconds.


In [55]:
"""tensordot()メソッドは、２つのテンソルの縮約に使う。
指定した軸上で２つのテンソルの積の和をとることで、次元を削減する。

"""
a = np.arange(60).reshape(3,4,5)
b = np.arange(24).reshape(4,3,2)
c = np.tensordot(a,b, axes=([1,0],[0,1]))
print(a)
print(b)
c

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]


array([[4400, 4730],
       [4532, 4874],
       [4664, 5018],
       [4796, 5162],
       [4928, 5306]])

In [56]:
"""上記ブロックは以下のコードを計算しているのと同じ"""
d = np.zeros((5, 2))
for i in range(5):
    for j in range(2):
        for k in range(3):
            for l in range(4):
                d[i,j] += a[k,l,i] * b[l,k,j]
d

array([[4400., 4730.],
       [4532., 4874.],
       [4664., 5018.],
       [4796., 5162.],
       [4928., 5306.]])

In [64]:
"""固有値・固有ベクトルを計算する np.linalg.eig()
固有値・固有ベクトルって何？
https://atarimae.biz/archives/24166
"""
a = np.array([[3,1],[0,2]])
# 固有値をv、固有ベクトルをwに代入
v, w = np.linalg.eig(a)
w

array([[ 1.        , -0.70710678],
       [ 0.        ,  0.70710678]])

In [66]:
"""PCA:principal component analysis を実行！
「変数が3つ以上ある高次元のデータに対して、より低い次元でデータのばらつきを説明する」手法
"""
from sklearn import decomposition, datasets
from sklearn.preprocessing import StandardScaler

data = datasets.load_breast_cancer()
cancer = data.data
# fit_transformメソッドで、平均が０、標準偏差が１の分布になるようにする
cancer = StandardScaler().fit_transform(cancer)
cancer.shape

(569, 30)

In [69]:
"""データがどう変換されたか確認"""
before_transformation = data.data
print(before_transformation[:10,:1])

cancer[:10,:1]

[[17.99]
 [20.57]
 [19.69]
 [11.42]
 [20.29]
 [12.45]
 [18.25]
 [13.71]
 [13.  ]
 [12.46]]


array([[ 1.09706398],
       [ 1.82982061],
       [ 1.57988811],
       [-0.76890929],
       [ 1.75029663],
       [-0.47637467],
       [ 1.17090767],
       [-0.11851678],
       [-0.32016686],
       [-0.47353452]])

##### 標準化の計算式
$$
Z = \frac{x-\mu}{\sigma}\\ 
\quad\\
$$
###### Z：標準化された値   　x：標準化される値（元データにある値）  　 $\mu$：分布の平均  　　$\sigma$：分布の標準偏差


In [74]:
"""データを変換したら、np.linalg.eig()で固有値と固有ベクトルを計算するために
共分散行列を計算し、続いてそれらを分解に用いる
""" 
convariance_matrix = np.cov(cancer,rowvar=False)
# データセットには30の特徴があるので共分散行列の形状は」(30, 30)になる。
convariance_matrix.shape

(30, 30)

In [75]:
eig_val_cov, eig_vec_cov = np.linalg.eig(convariance_matrix)
eig_pairs = [(np.abs(eig_val_cov[i]), eig_vec_cov[:,i]) for i in range(len(eig_val_cov))]

In [77]:
"""除去する固有ベクトルを決定するために、固有値を降べきの順にソート　※「べき」とは指数のこと
結果、大きな固有値を持つ最初の２つの固有ベクトルが、データの分布に関する
情報を最も多く含んでいる
"""
sorted_pairs = eig_pairs.sort(key=lambda x: x[0], reverse=True)
for i in eig_pairs:
    print(i[0])

13.304990794374568
5.701374603726145
2.8229101550062334
1.9841275177302
1.65163324233012
1.2094822398029712
0.676408881700906
0.4774562546895071
0.41762878210781723
0.3513108748817337
0.29443315349116456
0.2616211613661211
0.24178242132831346
0.1572861492175933
0.09430069560105563
0.08000340447737676
0.05950361353043194
0.05271142221014812
0.04956470021298179
0.031214260553066572
0.030025663090428794
0.02748771133890438
0.024383691354590887
0.01808679398430555
0.015508527134418791
0.008192037117606663
0.006912612579184416
0.0015921360011975463
0.0007501214127190039
0.0001332790566640968


In [81]:
"""より低い次元作業空間を得るために残りを除去する。
最初の2つの固有ベクトルを水平にスタック、この行列と元データの掛け算を行って、
元データを新しい次元数の部分空間へ射影する。
結果、(569,30)から(569,2)へ変換された。これはPCAの処理で28個の特徴が除去されたことを意味する。
"""
matrix_w = np.hstack((eig_pairs[0][1].reshape(30,1), eig_pairs[1][1].reshape(30,1)))
print(matrix_w.shape)
transformed = matrix_w.T.dot(cancer.T)
transformed = transformed.T
print(transformed[0])
transformed.shape

(30, 2)
[9.19283683 1.94858307]


(569, 2)