#### 機械学習のための numpy

In [ ]:
""" int32 int64 の違いって何？
整数のタイプごとに、異なる範囲のストレージ容量がある
Int16 -- 2バイト-- (-32,768 to +32,767)
Int32 -- 4バイト-- (-2,147,483,648 to +2,147,483,647)
Int64 -- 8バイト-- (-9,223,372,036,854,775,808 to +9,223,372,036,854,775,807)
"""

"""パーセンタイルって何？
パーセンタイルは、データを大きさ順でならべて100個に区切り、
小さいほうからのどの位置にあるかを見るものです。
50パーセンタイルは、小さいほうから50/100のところにあるデータです。
"""

In [56]:
"""基本情報"""
import numpy as np
x = np.array([[1,4],[3,3]])
print(x)
print(type(x)) # 
print(x.shape) # 次元をタプルで返す
print(x.size) # 全要素数
print(x.ndim) # 配列の次元数
print(x.dtype) # 配列のデータ型
print(x.nbytes) # 消費バイト数

[[1 4]
 [3 3]]
<class 'numpy.ndarray'>
(2, 2)
4
2
int32
16


In [57]:
"""逆行列"""
x_t = np.linalg.inv(x) 
x_t

array([[-0.33333333,  0.44444444],
       [ 0.33333333, -0.11111111]])

In [58]:
"""行列とその逆行列の積は単位行列となる"""
i = x.dot(x_t)
i

array([[1., 0.],
       [0., 1.]])

In [59]:
"""単位行列はこのようにも作れる"""
i = np.identity(2)
i

array([[1., 0.],
       [0., 1.]])

In [60]:
"""行列ｘに単位行列を掛けると結果はｘに等しくなる"""
x.dot(i)

array([[1., 4.],
       [3., 3.]])

In [61]:
"""消費バイト数比較  (-2147483647 < 扱う数字 < 2147483648) なら int32で十分でしょう"""
x = np.array([[1,2,3],[4,5,6]], dtype = np.uint32) # uint（符号なし整数）
print(x.nbytes)
x = np.array([[1,2,3],[4,5,6]], dtype = np.float)
print(x.nbytes)
x = np.array([[1,2,3],[4,5,6]], dtype = np.complex)
print(x.nbytes)
x = np.array([[1,2,3],[4,5,6]], dtype = np.int64)
print(x.nbytes)

24
48
96
48


In [62]:
"""astype属性を使い新たなdtypeの配列にコピー"""
x = np.array([[1,2,3],[4,5,6]], dtype = np.uint32) 
x_copy_int = x.astype(np.float)
print(x_copy_int)
x # 元の配列のdtypeは変わらない

[[1. 2. 3.]
 [4. 5. 6.]]


array([[1, 2, 3],
       [4, 5, 6]], dtype=uint32)

In [63]:
"""
dtypeを変えるだけで配列の大きさが80MBから40MBに縮小する。
その代わり、小数点以下の精度は低くなる。小数点以下16桁から7桁に。
"""
big_data = np.random.rand(100000,100)
print(big_data.nbytes)
big_data_new = big_data.astype(np.float32)
print(big_data_new.nbytes)

80000000
40000000


In [64]:
"""リストではこんな簡単に計算出来なくて、要素を反復する必要が"""
my_list = [2, 14, 6, 8]
my_array = np.asarray(my_list)
my_array + 2 #  

array([ 4, 16,  8, 10])

In [65]:
"""配列作成の便利方法（開始、終了、間隔）"""
x = np.arange(3,7,0.5)
x

array([3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5])

In [66]:
"""いくつに分割したいかわかっている場合"""
x = np.linspace(1.2, 40.5, num=20)
x

array([ 1.2       ,  3.26842105,  5.33684211,  7.40526316,  9.47368421,
       11.54210526, 13.61052632, 15.67894737, 17.74736842, 19.81578947,
       21.88421053, 23.95263158, 26.02105263, 28.08947368, 30.15789474,
       32.22631579, 34.29473684, 36.36315789, 38.43157895, 40.5       ])

In [67]:
"""対数スケールの等比等比数列を返す"""
np.geomspace(1, 625, num=5)

array([  1.,   5.,  25., 125., 625.])

In [68]:
"""
開始値と終了値の間を対数スケールで均等に値を並べた配列を返す
下の場合、開始値が10**3で終了値が10**4
"""
np.logspace(3, 4, num=5)

array([ 1000.        ,  1778.27941004,  3162.27766017,  5623.4132519 ,
       10000.        ])

In [69]:
"""上記例のような大きな値を避けるには常用対数を用いる"""
np.logspace(np.log10(3), np.log10(4), num=5)

array([3.        , 3.2237098 , 3.46410162, 3.72241944, 4.        ])

In [73]:
"""配列同士を高速に比較"""
x = np.array([1,2,3,4])
y = np.array([1,2,3,3])
x == y

array([ True,  True,  True, False])

In [75]:
"""2つの配列の全要素同士が一致するか否かを1つの値で返す"""
x = np.array([1,2,3,4,5,6,7,8,1,2,3,4,5,6,7,8,1,2,3,4,5,6,7,8,9,9,9,9])
y = np.array([1,2,3,4,5,6,7,8,1,2,3,4,5,6,7,8,1,2,3,4,5,6,7,8,9,9,8,9])
np.array_equal(x,y)

False

In [77]:
x > y

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False,  True,
       False])

In [80]:
"""論理比較（AND）"""
x = np.array([0, 1, 0, 0], dtype=bool)
y = np.array([1, 1, 0, 1], dtype=bool)
np.logical_and(x,y)

array([False,  True, False, False])

In [81]:
"""論理比較（OR）"""
x = np.array([12,16,57,11])
np.logical_or(x < 13, x > 50)

array([ True, False,  True,  True])

In [82]:
"""指数、三角関数"""
print(np.exp(x))
print(np.sin(x))

[1.62754791e+05 8.88611052e+06 5.68572000e+24 5.98741417e+04]
[-0.53657292 -0.28790332  0.43616476 -0.99999021]


In [86]:
"""行列を希望の形状に"""
x = np.arange(9)
print(x)
y = x.reshape((3, 3))
y

[0 1 2 3 4 5 6 7 8]


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [90]:
"""行列の転置"""
y.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])